# For every commit or tag that is pushed, build an image from it and push this to docker hub

name: Deploy to partnersinhealth/percona-0.1-4

on:
  push:
    branches:
      - 'main'
    paths:
      - 'percona-0.1-4/**'
      - '.github/workflows/deploy-percona-0.1.4.yml'
  create:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and Push Docker Image
        uses: PIH/openmrs-contrib-distro-tools/.github/actions/build-and-push-docker@main
        with:
          image_name: partnersinhealth/percona-0.1-4
          context: ./percona-0.1-4
          version: ${{ github.ref_name }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          platforms: linux/amd64
