# For every commit or tag that is pushed, build an image from it and push this to docker hub

name: Deploy to partnersinhealth/p7zip

on:
  push:
    branches:
      - 'main'
    paths:
      - 'p7zip/**'
      - '.github/workflows/deploy-p7zip.yml'
  create:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and Push Docker Image
        uses: PIH/openmrs-contrib-distro-tools/.github/actions/build-and-push-docker@main
        with:
          image_name: partnersinhealth/p7zip
          context: ./p7zip
          version: ${{ github.ref_name }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
